#!/usr/bin/env python
"""Materialize a custom md-publisher theme from a spec JSON.

Reads a single-theme spec (the same shape a built-in theme has in
themes/theme-spec.json) and writes a theme directory at
~/.md-publisher/themes/<slug>/ containing:

    style.css            - WeasyPrint stylesheet (palette + fonts substituted in)
    cover.css            - per-theme cover-page styling (palette + fonts)
    mermaid-config.json  - mmdc config (palette + fonts)
    spec.json            - canonical record. Input palette/fonts are normalized
                           to snake_case keys (ink_soft, accent_alt, code_bg,
                           code_text, table_stripe; serif/sans/mono/display)
                           so lib.theme_loader.Palette / Fonts can read them
                           directly when the DOCX pipeline runs.
    preview.html         - small static preview of typography + palette

Usage:
    scaffold-theme.py --spec /tmp/my-theme.json [--force]

Spec schema (minimum fields):

    {
      "slug": "my-corp-light",
      "name": "my-corp",
      "mode": "light",
      "displayName": "My Corp Light",
      "tagline": "Brand-aligned editorial.",
      "fonts": {
        "display": "Charter, Georgia, serif",
        "body":    "Charter, Georgia, serif",
        "sans":    "Inter, system-ui, sans-serif",
        "mono":    "JetBrains Mono, Consolas, monospace"
      },
      "palette": {
        "bg":         "#FFFFFF",
        "paper":      "#FFFFFF",
        "ink":        "#111111",
        "inkSoft":    "#555555",
        "accent":     "#005FCC",
        "accentSoft": "#E0EBF8",
        "rule":       "#DDDDDD",
        "codeBg":     "#F5F5F5",
        "codeText":   "#111111"
      },
      "mermaid": {
        "tagStyling": {
          "ingress":   {"fill":"...", "stroke":"...", "color":"...", "strokeWidth":2},
          "core":      {"fill":"...", "stroke":"...", "color":"...", "strokeWidth":1},
          "transform": {"fill":"...", "stroke":"...", "color":"...", "strokeWidth":1},
          "bridge":    {"fill":"...", "stroke":"...", "color":"...", "strokeWidth":1}
        },
        "fontFamily": "Inter, sans-serif",
        "lineColor":  "#555555"
      }
    }

By default refuses to overwrite an existing theme directory. Pass --force
to overwrite.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


USER_THEMES_DIR = Path.home() / ".md-publisher" / "themes"

# Validation patterns for spec values that flow into style.css + preview.html.
# Substituted values land verbatim into HTML/CSS contexts; rejecting fishy
# input early prevents stylesheet/HTML injection from a hand-edited or
# third-party theme spec.
#   - hex colors: 3, 4, 6, or 8 hex digits with leading #.
#   - bare font names (post first_family()): ASCII letters/digits/space/
#     hyphen/underscore/dot. Covers "Source Han Sans CN", "JetBrains Mono",
#     "IBM Plex Mono", "Newsreader". Rejects values containing CSS/HTML
#     control characters (`;`, `{`, `}`, `<`, `>`, `"`, `'`, `\`, `/`).
_HEX_COLOR_RE = re.compile(r"^#[0-9A-Fa-f]{3,8}$")
_FONT_FAMILY_RE = re.compile(r"^[A-Za-z0-9 _\-.]+$")


def _validate_palette(palette: dict) -> None:
    """Reject palette entries that aren't well-formed hex colors.

    Raises SystemExit(2) with a clear error naming the offending field
    so a typo or malicious spec halts the scaffold before it writes any
    output.
    """
    for key, value in palette.items():
        if not isinstance(value, str) or not _HEX_COLOR_RE.match(value):
            sys.stderr.write(
                f"[scaffold-theme] palette.{key} not a valid hex color: "
                f"{value!r} (expected #RGB / #RGBA / #RRGGBB / #RRGGBBAA)\n"
            )
            raise SystemExit(2)


def _validate_font(label: str, family: str) -> None:
    """Reject font family values that contain HTML/CSS-meaningful chars."""
    if not isinstance(family, str) or not _FONT_FAMILY_RE.match(family):
        sys.stderr.write(
            f"[scaffold-theme] {label} not a valid bare family name: "
            f"{family!r} (expected letters/digits/space/-_./, no quotes)\n"
        )
        raise SystemExit(2)


STYLE_CSS_TEMPLATE = """/* {{display_name}} — generated by md-publisher theme-advisor.
 * Edit freely; spec.json holds the canonical color/font values used by
 * the publish pipeline's classDef injection. Visual tweaks here only
 * affect this stylesheet; theme-spec values are read from spec.json. */
:root {
    --font-display: {{font_display}};
    --font-body:    {{font_body}};
    --font-sans:    {{font_sans}};
    --font-mono:    {{font_mono}};

    --bg:         {{bg}};
    --paper:      {{paper}};
    --ink:        {{ink}};
    --ink-soft:   {{ink_soft}};
    --accent:     {{accent}};
    --accent-soft:{{accent_soft}};
    --rule:       {{rule}};
    --code-bg:    {{code_bg}};
    --code-text:  {{code_text}};

    --page-margin: 1in;
    --size-body: 11pt;
    --leading-body: 1.45;
}

@page {
    size: letter;
    margin: var(--page-margin);
    background: var(--bg);
    @bottom-center {
        content: counter(page);
        font-family: var(--font-sans);
        font-size: 9pt;
        color: var(--ink-soft);
    }
    @top-right {
        content: string(doc-title);
        font-family: var(--font-sans);
        font-size: 9pt;
        color: var(--ink-soft);
    }
}
@page :first {
    @top-right { content: ""; }
    @bottom-center { content: ""; }
}
@page landscape-table { size: letter landscape; margin: 0.75in; }
.landscape-page { page: landscape-table; }

html { font-family: var(--font-body); font-size: var(--size-body);
       line-height: var(--leading-body); color: var(--ink);
       widows: 3; orphans: 3; }
body { margin: 0; padding: 0; background: var(--bg); }

h1.doc-title { string-set: doc-title content(); }

h1, h2, h3, h4, h5, h6 {
    font-family: var(--font-display);
    color: var(--ink);
    line-height: 1.2;
    break-after: avoid-page;
    page-break-after: avoid;
}
h1 { font-size: 22pt; font-weight: 700; margin: 0 0 0.6em 0;
     padding-bottom: 0.25em; border-bottom: 2px solid var(--accent);
     bookmark-level: 1; break-before: page; page-break-before: always; }
h1.doc-title { break-before: auto; page-break-before: auto; margin-top: 0; }
h2 { font-size: 16pt; font-weight: 600; margin: 1.4em 0 0.5em 0;
     color: var(--accent); bookmark-level: 2; }
h3 { font-size: 13pt; font-weight: 600; margin: 1.1em 0 0.4em 0;
     bookmark-level: 3; border-left: 3px solid var(--accent);
     padding-left: 0.5em; }

p { margin: 0 0 0.6em 0; text-align: justify; hyphens: auto; }
a { color: var(--accent); text-decoration: none; border-bottom: 1px solid var(--rule); }
strong { font-weight: 600; }
em { font-style: italic; }

code { font-family: var(--font-mono); font-size: 0.9em;
       background: var(--code-bg); border: 1px solid var(--rule);
       border-radius: 3px; padding: 0.05em 0.3em; line-height: 1; overflow-wrap: anywhere; }
pre code { background: transparent; border: none; padding: 0;
           font-size: inherit; line-height: inherit; border-radius: 0; }

pre { font-family: var(--font-mono); font-size: 9pt; line-height: 1.4;
      background: var(--code-bg); color: var(--code-text);
      border: 1px solid var(--rule); border-left: 3px solid var(--accent);
      border-radius: 4px; padding: 0.7em 0.9em; margin: 0.8em 0;
      overflow: hidden; white-space: pre-wrap; word-wrap: break-word;
      break-inside: avoid; page-break-inside: avoid; }
.codehilite { margin: 0.8em 0; break-inside: avoid; page-break-inside: avoid; }
.codehilite pre { margin: 0; }

/* Code blocks inside list items */
li > .codehilite,
li > pre {
    margin: 0.5em 0; max-width: 100%;
    box-sizing: border-box; overflow-x: auto;
}

table { width: 100%; border-collapse: collapse; margin: 0.9em 0; font-size: 10pt;
        break-inside: avoid; page-break-inside: avoid; }
thead { display: table-header-group; }
th, td { padding: 0.45em 0.7em; border: 1px solid var(--rule);
         text-align: left; vertical-align: top; }
th { background: var(--accent-soft); font-family: var(--font-sans);
     font-weight: 600; font-size: 9.5pt; }
td code, th code { word-break: break-all; overflow-wrap: break-word; font-size: 0.85em; }
table.wide-table { font-size: 8.5pt; }
table.wide-table th, table.wide-table td { padding: 0.3em 0.5em; }

figure.mermaid { margin: 1em auto; text-align: center; background: var(--paper);
                 padding: 0.5em; break-inside: avoid; page-break-inside: avoid;
                 break-before: avoid; page-break-before: avoid; }
figure.mermaid svg { display: block; margin: 0 auto;
                     max-width: 100%; max-height: 6in;
                     width: auto; height: auto; }
figure.mermaid figcaption { font-family: var(--font-sans); font-size: 9pt;
                            color: var(--ink-soft); margin-top: 0.4em; }
figure.mermaid.oversized {
    break-before: page; break-after: page;
    page-break-before: always; page-break-after: always;
    break-inside: avoid; page-break-inside: avoid; margin: 0;
}
figure.mermaid.oversized svg { max-width: 6.5in; max-height: 9in;
                                width: auto; height: auto; }

nav#toc { font-family: var(--font-body); }
nav#toc a { display: flex; align-items: baseline; gap: 0.5em;
            color: var(--ink); border: none; }
nav#toc .toc-leader { flex: 1 1 auto; border-bottom: 1px dotted var(--rule);
                      transform: translateY(-3px); margin: 0 0.4em; }
nav#toc .toc-pageno { color: var(--accent); font-variant-numeric: tabular-nums; }
"""


MERMAID_CONFIG_TEMPLATE = {
    "theme": "base",
    "themeVariables": {
        # Core palette — primaryColor drives ER/class entity fills;
        # must NOT be pure white or mermaid computes white text.
        "background": "{{paper}}",
        "primaryColor": "{{accent_soft}}",
        "primaryTextColor": "{{ink}}",
        "primaryBorderColor": "{{accent}}",
        "secondaryColor": "{{code_bg}}",
        "secondaryTextColor": "{{ink}}",
        "secondaryBorderColor": "{{rule}}",
        "tertiaryColor": "{{accent_soft}}",
        "tertiaryTextColor": "{{ink}}",
        "tertiaryBorderColor": "{{accent}}",
        "lineColor": "{{line_color}}",
        "fontFamily": "{{mermaid_font}}",
        # Flowchart / generic node colors
        "mainBkg": "{{paper}}",
        "nodeBorder": "{{accent}}",
        "nodeTextColor": "{{ink}}",
        "edgeLabelBackground": "{{paper}}",
        "clusterBkg": "{{accent_soft}}",
        "clusterBorder": "{{rule}}",
        # Sequence diagram
        "actorBkg": "{{paper}}",
        "actorBorder": "{{accent}}",
        "actorTextColor": "{{ink}}",
        "actorLineColor": "{{ink_soft}}",
        "signalColor": "{{ink_soft}}",
        "signalTextColor": "{{ink}}",
        "noteBkgColor": "{{accent_soft}}",
        "noteTextColor": "{{ink}}",
        "noteBorderColor": "{{accent}}",
        "activationBkgColor": "{{code_bg}}",
        "activationBorderColor": "{{ink_soft}}",
        "labelTextColor": "{{ink}}",
        # State diagram
        "labelColor": "{{ink}}",
        "altBackground": "{{accent_soft}}",
        # Class diagram
        "classText": "{{ink}}",
        # ER diagram
        "attributeBackgroundColorEven": "{{paper}}",
        "attributeBackgroundColorOdd": "{{accent_soft}}",
        # Pie chart — 8 slices cycling accent variations
        "pie1": "{{accent}}",
        "pie2": "{{ink_soft}}",
        "pie3": "{{accent_soft}}",
        "pie4": "{{code_bg}}",
        "pie5": "{{rule}}",
        "pie6": "{{accent}}",
        "pie7": "{{ink_soft}}",
        "pie8": "{{accent_soft}}",
        "pieStrokeColor": "{{paper}}",
        "pieTitleTextColor": "{{ink}}",
        "pieLegendTextColor": "{{ink}}",
        # Gantt
        "sectionBkgColor": "{{accent_soft}}",
        "sectionBkgColor2": "{{paper}}",
        "taskBkgColor": "{{accent_soft}}",
        "activeTaskBkgColor": "{{accent}}",
        "activeTaskBorderColor": "{{accent}}",
        "doneTaskBkgColor": "{{rule}}",
        "doneTaskBorderColor": "{{ink_soft}}",
        "taskTextColor": "{{ink}}",
        "taskTextDarkColor": "{{ink}}",
        "gridColor": "{{rule}}",
        "todayLineColor": "{{accent}}",
    },
    "flowchart": {
        "htmlLabels": False,
        "useMaxWidth": True,
        "nodeSpacing": 30,
        "rankSpacing": 30,
    },
    "sequence": {
        "actorMargin": 50,
        "noteMargin": 10,
        "messageMargin": 35,
        "useMaxWidth": True,
    },
    "state": {
        "useMaxWidth": True,
    },
    "class": {
        "useMaxWidth": True,
    },
    "er": {
        "useMaxWidth": True,
    },
    "pie": {
        "useMaxWidth": True,
    },
    "gantt": {
        "useMaxWidth": True,
    },
    "mindmap": {
        "useMaxWidth": True,
    },
    "securityLevel": "loose",
    "htmlLabels": False,
}


COVER_CSS_TEMPLATE = """/* {{display_name}} cover styling. Generated by theme-advisor; safe to edit.
 * The pipeline reads this file and appends it after the universal cover-page
 * layout from lib/pipeline.py::_COVER_BASE_CSS. */
header.cover .cover-ornament {
    display: block;
    width: 48px;
    height: 3px;
    background: var(--accent);
    margin: 0;
}
header.cover .cover-title {
    font-family: var(--font-display, var(--font-body));
    font-size: 36pt;
    font-weight: 700;
    color: var(--accent);
}
header.cover .cover-rule-top {
    display: block;
    width: 2.4in;
    height: 0.5px;
    background: var(--rule);
    margin: 0;
}
header.cover .cover-rule {
    width: 2.4in;
    height: 2px;
    background: var(--accent);
    margin: 3px 0 0 0;
}
header.cover .cover-rule-bottom {
    display: block;
    width: 2.4in;
    height: 0.5px;
    background: var(--rule);
    margin: 3px 0 0.35in 0;
}
header.cover .cover-subtitle {
    font-family: var(--font-body);
    font-size: 16pt;
    font-style: italic;
    color: var(--ink-soft);
}
header.cover .cover-meta {
    font-family: var(--font-sans, var(--font-body));
    font-size: 11pt;
    color: var(--ink);
}
header.cover .cover-attribution {
    font-family: var(--font-sans, var(--font-body));
    font-size: 9pt;
    color: var(--ink-soft);
}
@page cover { background: var(--bg); }
"""


PREVIEW_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><title>{{display_name}} preview</title>
<style>
{{style_css_inline}}
.preview-page { width: 7in; margin: 1in auto; background: var(--bg); padding: 1in; }
.mermaid-fig { margin: 1.5em 0; padding: 0.5em; background: var(--paper); border: 1px solid var(--rule); border-radius: 4px; }
.mermaid-fig figcaption { font-family: var(--font-sans); font-size: 9pt; color: var(--ink-soft); margin-top: 0.4em; text-align: center; }
.mermaid-fig svg { display: block; margin: 0 auto; max-width: 100%; height: auto; }
.mermaid-source { font-family: var(--font-mono); font-size: 0.8em; background: var(--code-bg); padding: 0.5em; overflow-x: auto; }
.mermaid-fallback-note { font-family: var(--font-sans); font-size: 8pt; color: var(--ink-soft); font-style: italic; }
</style></head>
<body><div class="preview-page">
<h1>{{display_name}}</h1>
<p style="color: var(--ink-soft); font-style: italic;">{{tagline}}</p>
<h2>Section heading</h2>
<p>The quick brown fox jumps over the lazy dog. Body text in <em>{{font_body_first}}</em>; an <a href="#">accent link</a> like this.</p>
<h3>Subsection heading</h3>
<p>The h3 level uses an accent left border to create visual hierarchy without overwhelming the page.</p>
<pre><code>def example():
    return "code block"</code></pre>
<table><thead><tr><th>Column</th><th>Column</th></tr></thead>
<tbody><tr><td>Row data</td><td>More data</td></tr></tbody></table>

<h2>Diagram preview</h2>
<figure class="mermaid-fig">
{{flowchart_figure}}
<figcaption>Flowchart with classDef tags</figcaption>
</figure>
<figure class="mermaid-fig">
{{er_figure}}
<figcaption>ER diagram (themed via mermaid-config)</figcaption>
</figure>
<figure class="mermaid-fig">
{{class_figure}}
<figcaption>Class diagram with <code>:::ingress</code> header tag</figcaption>
</figure>

<p style="margin-top: 1em; font-family: var(--font-sans); font-size: 9pt; color: var(--ink-soft);">
&mdash; {{display_name}} &middot; theme preview</p>
</div></body></html>
"""


def substitute(template: str, values: dict) -> str:
    out = template
    for key, val in values.items():
        out = out.replace("{{" + key + "}}", str(val))
    return out


def first_family(stack: str) -> str:
    """'Charter, Georgia, serif' -> 'Charter'"""
    return stack.split(",")[0].strip().strip('"').strip("'")


# Sample diagram sources used in preview.html. Each should render with the
# theme applied so the author can verify ER alternating rows, classDiagram
# header tagging, and the four flowchart classDef colors before publishing.

PREVIEW_FLOWCHART = """flowchart LR
    classDef ingress   {{ingress_classdef}}
    classDef core      {{core_classdef}}
    classDef transform {{transform_classdef}}
    classDef bridge    {{bridge_classdef}}
    A[Input]:::ingress --> B[Validate]:::transform
    B --> C[Process]:::core
    C --> D{Decision}:::bridge
    D --> E[Output]:::ingress
"""

PREVIEW_ER = """erDiagram
    CUSTOMER {
        string id PK
        string name
        string email
    }
    ORDER {
        string id PK
        string customer_id FK
        decimal total
        date placed_at
    }
    CUSTOMER ||--o{ ORDER : places
"""

PREVIEW_CLASS = """classDiagram
    class Engine:::ingress {
        +run()
        +stop()
    }
    class Worker {
        +process(task)
    }
    class Queue {
        +enqueue(item)
        +dequeue() item
    }
    Engine --> Queue
    Engine --> Worker
    Worker --> Queue
"""


def _classdef_props(style: dict) -> str:
    """Render a tagStyling style dict into a mermaid classDef rhs string."""
    parts = []
    for k, v in style.items():
        if k == "strokeWidth":
            parts.append(f"stroke-width:{v}")
        elif k == "strokeDasharray":
            parts.append(f"stroke-dasharray:{v}")
        else:
            parts.append(f"{k}:{v}")
    return ",".join(parts)


def _render_mermaid_to_svg(mermaid_src: str, mermaid_config_path: Path,
                           build_dir: Path, mmdc_path: Path) -> str | None:
    """Render a mermaid source via mmdc; return SVG string, or None on failure.

    Failures (mmdc missing, render error, timeout) return None so the caller
    can fall back to embedding the source. Preview rendering is non-blocking —
    the theme files are still produced regardless.
    """
    import subprocess as _sp
    if not mmdc_path.exists():
        return None
    src_path = build_dir / "preview.mmd"
    out_path = build_dir / "preview.svg"
    src_path.write_text(mermaid_src, encoding="utf-8")
    try:
        _sp.run(
            ["node", str(mmdc_path),
             "-i", str(src_path), "-o", str(out_path),
             "-c", str(mermaid_config_path),
             "-b", "transparent"],
            check=True, capture_output=True, timeout=30,
        )
    except (_sp.CalledProcessError, _sp.TimeoutExpired, FileNotFoundError):
        return None
    if not out_path.exists():
        return None
    return out_path.read_text(encoding="utf-8")


def _render_preview_figure(mermaid_src: str, mermaid_config_path: Path,
                           build_dir: Path, mmdc_path: Path) -> str:
    """Render `mermaid_src` via mmdc; on failure, return a fallback HTML block."""
    svg = _render_mermaid_to_svg(mermaid_src, mermaid_config_path, build_dir, mmdc_path)
    if svg:
        # Strip any leading XML declaration; we're inlining
        return re.sub(r"^<\?xml[^>]*\?>\s*", "", svg)
    escaped = mermaid_src.replace("&", "&amp;").replace("<", "&lt;")
    return (
        f'<pre class="mermaid-source">{escaped}</pre>'
        f'<p class="mermaid-fallback-note">'
        f'(install runtime then re-scaffold to see live diagrams)</p>'
    )


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--spec", type=Path, required=True, help="path to spec JSON")
    p.add_argument("--force", action="store_true",
                   help="overwrite an existing theme directory")
    args = p.parse_args()

    if not args.spec.exists():
        sys.stderr.write(f"[scaffold-theme] spec not found: {args.spec}\n")
        return 2
    spec = json.loads(args.spec.read_text(encoding="utf-8"))

    # Required fields
    for field in ("slug", "fonts", "palette", "mermaid"):
        if field not in spec:
            sys.stderr.write(f"[scaffold-theme] spec missing required field: {field}\n")
            return 2

    slug = spec["slug"]
    target = USER_THEMES_DIR / slug

    if target.exists() and not args.force:
        sys.stderr.write(
            f"[scaffold-theme] theme already exists: {target}\n"
            "Use --force to overwrite, or pick a different slug.\n"
        )
        return 1

    target.mkdir(parents=True, exist_ok=True)

    palette = spec["palette"]
    fonts = spec["fonts"]

    # Required palette fields (no fallback): missing these would crash
    # the substitute calls below with KeyError mid-write.
    for required in ("bg", "ink", "accent"):
        if required not in palette:
            sys.stderr.write(
                f"[scaffold-theme] palette missing required field: {required}\n"
            )
            return 2

    # Validate every value flowing into HTML/CSS contexts. Rejects
    # injection-shaped strings (CSS/HTML control chars, non-hex colors)
    # before any output file is written.
    _validate_palette(palette)
    for key, default in (("display", "serif"), ("body", "serif"),
                         ("sans", "sans-serif"), ("mono", "monospace")):
        family = fonts.get(key, default)
        # The values that flow into output files are always passed through
        # first_family() (style.css uses raw stack but only its own
        # template; preview.html + spec.json use bare). Validate the bare
        # form to catch any injection chars before the stack-strip too.
        _validate_font(f"fonts.{key}", first_family(family))
    if "lineColor" in spec["mermaid"]:
        if not _HEX_COLOR_RE.match(str(spec["mermaid"]["lineColor"])):
            sys.stderr.write(
                f"[scaffold-theme] mermaid.lineColor not a hex color: "
                f"{spec['mermaid']['lineColor']!r}\n"
            )
            return 2

    line_color = spec["mermaid"].get("lineColor", palette.get("accent", "#555555"))
    mermaid_font = spec["mermaid"].get("fontFamily", fonts.get("sans", "sans-serif"))
    display_name = spec.get("displayName", slug)
    tagline = spec.get("tagline", "Custom md-publisher theme.")

    style_subs = {
        "display_name": display_name,
        "font_display": fonts.get("display", "serif"),
        "font_body":    fonts.get("body", "serif"),
        "font_sans":    fonts.get("sans", "sans-serif"),
        "font_mono":    fonts.get("mono", "monospace"),
        "bg":           palette["bg"],
        "paper":        palette.get("paper", palette["bg"]),
        "ink":          palette["ink"],
        "ink_soft":     palette.get("inkSoft", palette["ink"]),
        "accent":       palette["accent"],
        "accent_soft":  palette.get("accentSoft", palette["accent"]),
        "rule":         palette.get("rule", palette.get("inkSoft", "#cccccc")),
        "code_bg":      palette.get("codeBg", palette.get("paper", palette["bg"])),
        "code_text":    palette.get("codeText", palette["ink"]),
    }
    style_css = substitute(STYLE_CSS_TEMPLATE, style_subs)
    (target / "style.css").write_text(style_css, encoding="utf-8")

    cover_css = substitute(COVER_CSS_TEMPLATE, style_subs)
    (target / "cover.css").write_text(cover_css, encoding="utf-8")

    mermaid_subs = {
        **style_subs,
        "line_color": line_color,
        "mermaid_font": mermaid_font,
    }
    mermaid_cfg_str = substitute(json.dumps(MERMAID_CONFIG_TEMPLATE, indent=2), mermaid_subs)
    # Validate it round-trips through json (catches typos in templates)
    json.loads(mermaid_cfg_str)
    (target / "mermaid-config.json").write_text(mermaid_cfg_str, encoding="utf-8")

    # Spec.json — persist the input but normalize palette + fonts to the
    # snake_case keys lib.theme_loader.Palette/Fonts expects so DOCX output
    # honors brand palette/fonts without the CSS-extraction fallback.
    persisted = dict(spec)
    persisted["palette"] = {
        "bg":           palette["bg"],
        "paper":        palette.get("paper", palette["bg"]),
        "ink":          palette["ink"],
        "ink_soft":     palette.get("inkSoft", palette["ink"]),
        "accent":       palette["accent"],
        "accent_alt":   palette.get("accentSoft", palette["accent"]),
        "rule":         palette.get("rule", palette.get("inkSoft", palette["ink"])),
        "code_bg":      palette.get("codeBg", palette.get("paper", palette["bg"])),
        "code_text":    palette.get("codeText", palette["ink"]),
        "table_stripe": palette.get("tableStripe", palette.get("paper", palette["bg"])),
    }
    # Persist bare family names (not CSS stacks) — Word's <w:rFonts> + the
    # install-fonts skill's OS lookup both need a single resolvable family.
    # Input fonts.body/sans/mono/display are CSS stacks per the docstring;
    # first_family() drops everything after the first comma.
    body = fonts.get("body", fonts.get("display", "serif"))
    persisted["fonts"] = {
        "serif":   first_family(body),
        "sans":    first_family(fonts.get("sans", "sans-serif")),
        "mono":    first_family(fonts.get("mono", "monospace")),
        "display": first_family(fonts.get("display", body)),
    }
    (target / "spec.json").write_text(
        json.dumps(persisted, indent=2), encoding="utf-8"
    )

    # Preview HTML — renders three mermaid figures (flowchart, ER, class)
    # using mmdc so the author can verify diagram styling before publishing.
    # Falls back to source blocks if the mmdc runtime isn't bootstrapped.
    mmdc_path = (
        Path.home() / ".md-publisher" / "runtime" / "node_modules"
        / "@mermaid-js" / "mermaid-cli" / "src" / "cli.js"
    )
    build_dir = target / ".preview-build"
    build_dir.mkdir(exist_ok=True)
    mermaid_config_path = target / "mermaid-config.json"

    flowchart_src = substitute(PREVIEW_FLOWCHART, {
        "ingress_classdef":   _classdef_props(spec["mermaid"]["tagStyling"]["ingress"]),
        "core_classdef":      _classdef_props(spec["mermaid"]["tagStyling"]["core"]),
        "transform_classdef": _classdef_props(spec["mermaid"]["tagStyling"]["transform"]),
        "bridge_classdef":    _classdef_props(spec["mermaid"]["tagStyling"]["bridge"]),
    })
    flowchart_figure = _render_preview_figure(flowchart_src, mermaid_config_path, build_dir, mmdc_path)
    er_figure = _render_preview_figure(PREVIEW_ER, mermaid_config_path, build_dir, mmdc_path)
    class_figure = _render_preview_figure(PREVIEW_CLASS, mermaid_config_path, build_dir, mmdc_path)

    # Cleanup the build dir; failures here are non-fatal.
    import shutil
    try:
        shutil.rmtree(build_dir)
    except OSError:
        pass

    preview_subs = {
        **style_subs,
        "tagline": tagline,
        "font_body_first": first_family(body),
        "style_css_inline": style_css,
        "flowchart_figure": flowchart_figure,
        "er_figure":        er_figure,
        "class_figure":     class_figure,
    }
    preview_html = substitute(PREVIEW_HTML_TEMPLATE, preview_subs)
    (target / "preview.html").write_text(preview_html, encoding="utf-8")

    print(f"[scaffold-theme] wrote theme to: {target}")
    print(f"  style.css            ({len(style_css)} bytes)")
    print(f"  mermaid-config.json  ({len(mermaid_cfg_str)} bytes)")
    print(f"  spec.json")
    print(f"  preview.html         (open in a browser to see the theme)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
