#!/usr/bin/env python
"""Materialize a custom md-publisher theme from a spec JSON.

Reads a single-theme spec (the same shape a built-in theme has in
themes/theme-spec.json) and writes a theme directory at
~/.md-publisher/themes/<slug>/ containing:

    style.css            - WeasyPrint stylesheet (palette + fonts substituted in)
    mermaid-config.json  - mmdc config (palette + fonts)
    spec.json            - canonical record. Input palette/fonts are normalized
                           to snake_case keys (ink_soft, accent_alt, code_bg,
                           code_text, table_stripe; serif/sans/mono/display)
                           so lib.theme_loader.Palette / Fonts can read them
                           directly when the DOCX pipeline runs.
    preview.html         - small static preview of typography + palette

Usage:
    scaffold-theme.py --spec /tmp/my-theme.json [--force]

Spec schema (minimum fields):

    {
      "slug": "my-corp-light",
      "name": "my-corp",
      "mode": "light",
      "displayName": "My Corp Light",
      "tagline": "Brand-aligned editorial.",
      "fonts": {
        "display": "Charter, Georgia, serif",
        "body":    "Charter, Georgia, serif",
        "sans":    "Inter, system-ui, sans-serif",
        "mono":    "JetBrains Mono, Consolas, monospace"
      },
      "palette": {
        "bg":         "#FFFFFF",
        "paper":      "#FFFFFF",
        "ink":        "#111111",
        "inkSoft":    "#555555",
        "accent":     "#005FCC",
        "accentSoft": "#E0EBF8",
        "rule":       "#DDDDDD",
        "codeBg":     "#F5F5F5",
        "codeText":   "#111111"
      },
      "mermaid": {
        "tagStyling": {
          "ingress":   {"fill":"...", "stroke":"...", "color":"...", "strokeWidth":2},
          "core":      {"fill":"...", "stroke":"...", "color":"...", "strokeWidth":1},
          "transform": {"fill":"...", "stroke":"...", "color":"...", "strokeWidth":1},
          "bridge":    {"fill":"...", "stroke":"...", "color":"...", "strokeWidth":1}
        },
        "fontFamily": "Inter, sans-serif",
        "lineColor":  "#555555"
      }
    }

By default refuses to overwrite an existing theme directory. Pass --force
to overwrite.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


USER_THEMES_DIR = Path.home() / ".md-publisher" / "themes"


STYLE_CSS_TEMPLATE = """/* {{display_name}} — generated by md-publisher theme-advisor.
 * Edit freely; spec.json holds the canonical color/font values used by
 * the publish pipeline's classDef injection. Visual tweaks here only
 * affect this stylesheet; theme-spec values are read from spec.json. */
:root {
    --font-display: {{font_display}};
    --font-body:    {{font_body}};
    --font-sans:    {{font_sans}};
    --font-mono:    {{font_mono}};

    --bg:         {{bg}};
    --paper:      {{paper}};
    --ink:        {{ink}};
    --ink-soft:   {{ink_soft}};
    --accent:     {{accent}};
    --accent-soft:{{accent_soft}};
    --rule:       {{rule}};
    --code-bg:    {{code_bg}};
    --code-text:  {{code_text}};

    --page-margin: 1in;
    --size-body: 11pt;
    --leading-body: 1.45;
}

@page {
    size: letter;
    margin: var(--page-margin);
    background: var(--bg);
    @bottom-center {
        content: counter(page);
        font-family: var(--font-sans);
        font-size: 9pt;
        color: var(--ink-soft);
    }
    @top-right {
        content: string(doc-title);
        font-family: var(--font-sans);
        font-size: 9pt;
        color: var(--ink-soft);
    }
}
@page :first {
    @top-right { content: ""; }
    @bottom-center { content: ""; }
}

html { font-family: var(--font-body); font-size: var(--size-body);
       line-height: var(--leading-body); color: var(--ink);
       widows: 3; orphans: 3; }
body { margin: 0; padding: 0; background: var(--bg); }

h1.doc-title { string-set: doc-title content(); }

h1, h2, h3, h4, h5, h6 {
    font-family: var(--font-display);
    color: var(--ink);
    line-height: 1.2;
    break-after: avoid-page;
    page-break-after: avoid;
}
h1 { font-size: 22pt; font-weight: 700; margin: 0 0 0.6em 0;
     padding-bottom: 0.25em; border-bottom: 2px solid var(--accent);
     bookmark-level: 1; break-before: page; page-break-before: always; }
h1.doc-title { break-before: auto; page-break-before: auto; margin-top: 0; }
h2 { font-size: 16pt; font-weight: 600; margin: 1.4em 0 0.5em 0;
     color: var(--accent); bookmark-level: 2; }
h3 { font-size: 13pt; font-weight: 600; margin: 1.1em 0 0.4em 0;
     bookmark-level: 3; }

p { margin: 0 0 0.6em 0; text-align: justify; hyphens: auto; }
a { color: var(--accent); text-decoration: none; border-bottom: 1px solid var(--rule); }
strong { font-weight: 600; }
em { font-style: italic; }

code { font-family: var(--font-mono); font-size: 0.9em;
       background: var(--code-bg); border: 1px solid var(--rule);
       border-radius: 3px; padding: 0.05em 0.3em; line-height: 1; }
pre code { background: transparent; border: none; padding: 0;
           font-size: inherit; line-height: inherit; border-radius: 0; }

pre { font-family: var(--font-mono); font-size: 9pt; line-height: 1.4;
      background: var(--code-bg); color: var(--code-text);
      border: 1px solid var(--rule); border-left: 3px solid var(--accent);
      border-radius: 4px; padding: 0.7em 0.9em; margin: 0.8em 0;
      overflow: hidden; white-space: pre-wrap; word-wrap: break-word;
      break-inside: avoid; page-break-inside: avoid; }
.codehilite { margin: 0.8em 0; break-inside: avoid; page-break-inside: avoid; }
.codehilite pre { margin: 0; }

table { width: 100%; border-collapse: collapse; margin: 0.9em 0; font-size: 10pt;
        break-inside: avoid; page-break-inside: avoid; }
thead { display: table-header-group; }
th, td { padding: 0.45em 0.7em; border: 1px solid var(--rule);
         text-align: left; vertical-align: top; }
th { background: var(--accent-soft); font-family: var(--font-sans);
     font-weight: 600; font-size: 9.5pt; }

figure.mermaid { margin: 1em auto; text-align: center; background: var(--paper);
                 padding: 0.5em; break-inside: avoid; page-break-inside: avoid;
                 break-before: avoid; page-break-before: avoid; }
figure.mermaid svg { display: block; margin: 0 auto;
                     max-width: 100%; max-height: 6in;
                     width: auto; height: auto; }
figure.mermaid figcaption { font-family: var(--font-sans); font-size: 9pt;
                            color: var(--ink-soft); margin-top: 0.4em; }
figure.mermaid.oversized {
    break-before: page; break-after: page;
    page-break-before: always; page-break-after: always;
    break-inside: avoid; page-break-inside: avoid; margin: 0;
}
figure.mermaid.oversized svg { max-width: 6.5in; max-height: 9in;
                                width: auto; height: auto; }

nav#toc { font-family: var(--font-body); }
nav#toc a { display: flex; align-items: baseline; gap: 0.5em;
            color: var(--ink); border: none; }
nav#toc .toc-leader { flex: 1 1 auto; border-bottom: 1px dotted var(--rule);
                      transform: translateY(-3px); margin: 0 0.4em; }
nav#toc .toc-pageno { color: var(--accent); font-variant-numeric: tabular-nums; }
"""


MERMAID_CONFIG_TEMPLATE = {
    "theme": "base",
    "themeVariables": {
        "background": "{{paper}}",
        "primaryColor": "{{paper}}",
        "primaryTextColor": "{{ink}}",
        "primaryBorderColor": "{{ink_soft}}",
        "lineColor": "{{line_color}}",
        "tertiaryColor": "{{accent}}",
        "fontFamily": "{{mermaid_font}}",
    },
    "flowchart": {
        "htmlLabels": False,
        "useMaxWidth": True,
        "nodeSpacing": 30,
        "rankSpacing": 30,
    },
    "securityLevel": "loose",
}


COVER_CSS_TEMPLATE = """/* {{display_name}} cover styling. Generated by theme-advisor; safe to edit.
 * The pipeline reads this file and appends it after the universal cover-page
 * layout from lib/pipeline.py::_COVER_BASE_CSS. */
header.cover .cover-title {
    font-family: var(--font-display, var(--font-body));
    font-size: 36pt;
    font-weight: 700;
    color: var(--accent);
}
header.cover .cover-rule {
    width: 1.4in;
    height: 2px;
    background: var(--accent);
}
header.cover .cover-subtitle {
    font-family: var(--font-body);
    font-size: 16pt;
    font-style: italic;
    color: var(--ink-soft);
}
header.cover .cover-meta {
    font-family: var(--font-sans, var(--font-body));
    font-size: 11pt;
    color: var(--ink);
}
header.cover .cover-attribution {
    font-family: var(--font-sans, var(--font-body));
    font-size: 9pt;
    color: var(--ink-soft);
}
@page cover { background: var(--bg); }
"""


PREVIEW_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><title>{{display_name}} preview</title>
<style>
{{style_css_inline}}
.preview-page { width: 7in; margin: 1in auto; background: var(--bg); padding: 1in; }
</style></head>
<body><div class="preview-page">
<h1>{{display_name}}</h1>
<p style="color: var(--ink-soft); font-style: italic;">{{tagline}}</p>
<h2>Section heading</h2>
<p>The quick brown fox jumps over the lazy dog. Body text in <em>{{font_body_first}}</em>; an <a href="#">accent link</a> like this.</p>
<pre><code>def example():
    return "code block"</code></pre>
<table><thead><tr><th>Column</th><th>Column</th></tr></thead>
<tbody><tr><td>Row data</td><td>More data</td></tr></tbody></table>
<p style="margin-top: 1em; font-family: var(--font-sans); font-size: 9pt; color: var(--ink-soft);">
&mdash; {{display_name}} &middot; theme preview</p>
</div></body></html>
"""


def substitute(template: str, values: dict) -> str:
    out = template
    for key, val in values.items():
        out = out.replace("{{" + key + "}}", str(val))
    return out


def first_family(stack: str) -> str:
    """'Charter, Georgia, serif' -> 'Charter'"""
    return stack.split(",")[0].strip().strip('"').strip("'")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--spec", type=Path, required=True, help="path to spec JSON")
    p.add_argument("--force", action="store_true",
                   help="overwrite an existing theme directory")
    args = p.parse_args()

    if not args.spec.exists():
        sys.stderr.write(f"[scaffold-theme] spec not found: {args.spec}\n")
        return 2
    spec = json.loads(args.spec.read_text(encoding="utf-8"))

    # Required fields
    for field in ("slug", "fonts", "palette", "mermaid"):
        if field not in spec:
            sys.stderr.write(f"[scaffold-theme] spec missing required field: {field}\n")
            return 2

    slug = spec["slug"]
    target = USER_THEMES_DIR / slug

    if target.exists() and not args.force:
        sys.stderr.write(
            f"[scaffold-theme] theme already exists: {target}\n"
            "Use --force to overwrite, or pick a different slug.\n"
        )
        return 1

    target.mkdir(parents=True, exist_ok=True)

    palette = spec["palette"]
    fonts = spec["fonts"]
    line_color = spec["mermaid"].get("lineColor", palette.get("inkSoft", "#555555"))
    mermaid_font = spec["mermaid"].get("fontFamily", fonts.get("sans", "sans-serif"))
    display_name = spec.get("displayName", slug)
    tagline = spec.get("tagline", "Custom md-publisher theme.")

    style_subs = {
        "display_name": display_name,
        "font_display": fonts.get("display", "serif"),
        "font_body":    fonts.get("body", "serif"),
        "font_sans":    fonts.get("sans", "sans-serif"),
        "font_mono":    fonts.get("mono", "monospace"),
        "bg":           palette["bg"],
        "paper":        palette.get("paper", palette["bg"]),
        "ink":          palette["ink"],
        "ink_soft":     palette.get("inkSoft", palette["ink"]),
        "accent":       palette["accent"],
        "accent_soft":  palette.get("accentSoft", palette["accent"]),
        "rule":         palette.get("rule", palette.get("inkSoft", "#cccccc")),
        "code_bg":      palette.get("codeBg", palette.get("paper", palette["bg"])),
        "code_text":    palette.get("codeText", palette["ink"]),
    }
    style_css = substitute(STYLE_CSS_TEMPLATE, style_subs)
    (target / "style.css").write_text(style_css, encoding="utf-8")

    cover_css = substitute(COVER_CSS_TEMPLATE, style_subs)
    (target / "cover.css").write_text(cover_css, encoding="utf-8")

    mermaid_subs = {
        **style_subs,
        "line_color": line_color,
        "mermaid_font": mermaid_font,
    }
    mermaid_cfg_str = substitute(json.dumps(MERMAID_CONFIG_TEMPLATE, indent=2), mermaid_subs)
    # Validate it round-trips through json (catches typos in templates)
    json.loads(mermaid_cfg_str)
    (target / "mermaid-config.json").write_text(mermaid_cfg_str, encoding="utf-8")

    # Spec.json — persist the input but normalize palette + fonts to the
    # snake_case keys lib.theme_loader.Palette/Fonts expects so DOCX output
    # honors brand palette/fonts without the CSS-extraction fallback.
    persisted = dict(spec)
    persisted["palette"] = {
        "bg":           palette["bg"],
        "paper":        palette.get("paper", palette["bg"]),
        "ink":          palette["ink"],
        "ink_soft":     palette.get("inkSoft", palette["ink"]),
        "accent":       palette["accent"],
        "accent_alt":   palette.get("accentSoft", palette["accent"]),
        "rule":         palette.get("rule", palette.get("inkSoft", palette["ink"])),
        "code_bg":      palette.get("codeBg", palette.get("paper", palette["bg"])),
        "code_text":    palette.get("codeText", palette["ink"]),
        "table_stripe": palette.get("tableStripe", palette.get("paper", palette["bg"])),
    }
    # Persist bare family names (not CSS stacks) — Word's <w:rFonts> + the
    # install-fonts skill's OS lookup both need a single resolvable family.
    # Input fonts.body/sans/mono/display are CSS stacks per the docstring;
    # first_family() drops everything after the first comma.
    body = fonts.get("body", fonts.get("display", "serif"))
    persisted["fonts"] = {
        "serif":   first_family(body),
        "sans":    first_family(fonts.get("sans", "sans-serif")),
        "mono":    first_family(fonts.get("mono", "monospace")),
        "display": first_family(fonts.get("display", body)),
    }
    (target / "spec.json").write_text(
        json.dumps(persisted, indent=2), encoding="utf-8"
    )

    # Preview HTML — uses the same generated style.css inline
    preview_subs = {
        **style_subs,
        "tagline": tagline,
        "font_body_first": first_family(fonts.get("body", "serif")),
        "style_css_inline": style_css,
    }
    preview_html = substitute(PREVIEW_HTML_TEMPLATE, preview_subs)
    (target / "preview.html").write_text(preview_html, encoding="utf-8")

    print(f"[scaffold-theme] wrote theme to: {target}")
    print(f"  style.css            ({len(style_css)} bytes)")
    print(f"  mermaid-config.json  ({len(mermaid_cfg_str)} bytes)")
    print(f"  spec.json")
    print(f"  preview.html         (open in a browser to see the theme)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
